version: '3'

services:
  app:
    build: ./app
    env_file: .env
    volumes:
      - ./app:/home/node/app
    entrypoint:
      /home/node/app/entrypoint.sh
    ports:
      - "3002:3002"

  db:
    image: "mongo:3.2.20-jessie"
    env_file: .env
    volumes:
      - groupdata:/data/db
    ports:
      - "27017:27018"

volumes:
  groupdata: